
name: Github-actions-Self-hosted demo

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag Name'
        required: true
        default: 'latest'

jobs:
  build_and_push:
    runs-on: self-hosted

    env:
      java-version: 21
      java-distribution: 'temurin'
      java-cache: maven
      TAG_NAME: ${{ github.event.inputs.TAG_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Maven project
        run: mvn clean install

      #Test Env variable and use
      - name: SetUp java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-distribution }}
          cache: ${{ env.java-cache }}

      #GitHub Repositority path print
      - name: Print GitHub Repository Path
        run: echo $GITHUB_REPOSITORY

      # Test secret in GitHub vault
      - name: Test Secret
        run: echo ${{ secrets.TEST_SECRET_NAME }}

      - name: Test the Tag Name
        run: echo ${{ env.TAG_NAME }}


