
name: Github-actions-Self-hosted demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: self-hosted

    env:
      java-version: 21
      java-distribution: 'temurin'
      java-cache: maven

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SetUp java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-distribution }}
          cache: ${{ env.java-cache }}

      - name: Build Maven project
        run: mvn clean install

